# Generated by Django 4.2.4 on 2023-09-08 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("HW", "0003_benfordconf"),
    ]

    operations = [
        migrations.RenameField(
            model_name="benfordconf",
            old_name="delimitter",
            new_name="delimiter",
        ),
    ]
