# Generated by Django 4.2.4 on 2023-09-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HW", "0004_rename_delimitter_benfordconf_delimiter"),
    ]

    operations = [
        migrations.AddField(
            model_name="benfordconf",
            name="separator",
            field=models.CharField(default=",", max_length=255),
        ),
        migrations.AlterField(
            model_name="benfordconf",
            name="delimiter",
            field=models.CharField(default='"', max_length=255),
        ),
    ]
