# Generated by Django 4.2.4 on 2023-09-08 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("HW", "0005_benfordconf_separator_alter_benfordconf_delimiter"),
    ]

    operations = [
        migrations.RenameField(
            model_name="benfordconf",
            old_name="separator",
            new_name="qoute",
        ),
    ]
