# Generated by Django 4.2.4 on 2023-09-08 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("HW", "0006_rename_separator_benfordconf_qoute"),
    ]

    operations = [
        migrations.RenameField(
            model_name="benfordconf",
            old_name="qoute",
            new_name="quote",
        ),
    ]
